import random

# Constants
MAX_RAINFALL = 128
LOW_RAIN_THRESHOLD = 32

# Initialize the list of plants with default values
plants = ["Parsley", "Sage", "Rosemary", "Thyme", "Broccolini", "Broccoli", "Now I Have Lots"]

# Initialize the total food available
total_food = sum([len(plant) for plant in plants])

# Simulate a day function
def simulate_day(total_food, plants):
    print(f"Rainfall: {rainfall}mm")
    
    # Check if any plants die due to low rainfall
    if rainfall < LOW_RAIN_THRESHOLD and plants:
        random_plant = random.choice(plants)
        plants.remove(random_plant)
        print(f"Sadly, your {random_plant} plant has died.")
    
    # Calculate and display food generated by each plant
    for plant in plants:
        percent = random.uniform(1/3 * rainfall, rainfall) / MAX_RAINFALL
        food_produced = int(percent * len(plant))
        print(f"{plant} produced {food_produced},", end=" ")
        total_food += food_produced
    
    print()
    print(f"After {days} days, you have {len(plants)} plants and your total food is {total_food}.")
    print("(W)ait")
    print("(D)isplay plants")
    print("(A)dd new plant")
    print("(Q)uit")

# Display welcome and instructions
print("Welcome to my garden.")
print("Plants cost and generate food according to their name length (e.g., Sage plants cost 4).")
print("You can purchase new plants with the food your garden generates.")
print("You get up to 128 mm of rain per day. Not all plants can survive with less than 32.")
print("Enjoy :)")

# Load plants from a file (optional)
load_plants = input("Would you like to load your plants from plants.txt (Y/n)? ")
if load_plants.lower() == "y":
    with open("plants.txt") as file:
        plants = [line.strip() for line in file]

print("You start with these plants:")
print(", ".join(plants))
print(f"After 0 days, you have {len(plants)} plants and your total food is {total_food}.")

# Main loop
days = 0
while True:
    print("(W)ait")
    print("(D)isplay plants")
    print("(A)dd new plant")
    print("(Q)uit")
    
    choice = input("Choose: ").upper()
    
    if choice == "D":
        print(", ".join(plants))
        print(f"After {days} days, you have {len(plants)} plants and your total food is {total_food}.")
    elif choice == "W":
        days += 1
        rainfall = random.randint(0, MAX_RAINFALL)
        simulate_day(total_food, plants)
    elif choice == "A":
        new_plant = input("Enter plant name: ").title()
        if new_plant and new_plant not in plants:
            if len(new_plant) <= total_food:
                plants.append(new_plant)
                total_food -= len(new_plant)
                print(f"You have added {new_plant} to your garden.")
            else:
                print(f"{new_plant} would cost {len(new_plant)} food. With only {total_food}, you can't afford it.")
        else:
            print(f"Invalid plant name or you already have {new_plant}.")
    elif choice == "Q":
        print("You finished with these plants:")
        print(", ".join(plants))
        print(f"After {days} days, you have {len(plants)} plants and your total food is {total_food}.")
        
        save_plants = input("Would you like to save your plants to plants.txt (Y/n)? ")
        if save_plants.lower() == "y":
            with open("plants.txt", "w") as file:
                for plant in plants:
                    file.write(plant + "\n")
            print("Saved.")
        
        print("Thank you for simulating. Now enjoy some real plants.")
        break
    else:
        print("Invalid choice")
